### ISSUE TITLE
Question on same-origin policy (SOP) across iframes

### ISSUE THREAD

**Issue by bitsofparag** [mergesort/WebViewController#1]
Does `WebViewController`'s webkit implementation allow access to web preferences so that one can disable SOP across iframes that have different origins? Or is it just a view controller built over the standard iOS Webkit library?

**Comment by mergesort** [comment]
Hey @paragmajum. It's just a view controller wrapping a `UIWebView`, with a couple of callbacks that allow you to customize what happens when you tap back, forward, and share. 

It does expose the `UIWebViewDelegate`, so you can customize it however you want.
